//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wlog.Library.BLL.Interfaces
{
    /// <summary>
    /// inteface for implementing UOW pattern in many storage system
    /// </summary>
    public interface IUnitOfWork:IDisposable
    {
        void BeginTransaction();
        void Commit();
        void SaveOrUpdate(IEntityBase entity);
        void Delete(IEntityBase entity);
        IQueryable<T> Query<T>();
    }
}
