//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System.ComponentModel.DataAnnotations;
using Wlog.Web.Filters;
using Wlog.Web.Resources;

namespace Wlog.Web.Models
{
    public class Password
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(ResourceType = typeof(Labels), Name = "OldPassword")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessageResourceType = typeof(Labels), ErrorMessageResourceName = "PasswordTooShort", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(ResourceType = typeof(Labels), Name = "NewPassword")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(ResourceType = typeof(Labels), Name = "Confirm")]
        [Compare("NewPassword", ErrorMessageResourceType = typeof(Labels), ErrorMessageResourceName = "PasswordMismatch")]
        public string ConfirmPassword { get; set; }
    }

    public class Email
    {
        [Required]
        [Display(ResourceType = typeof(Labels), Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string Address { get; set; }
    }

    public class LocalPasswordModel
    {
        [Display(ResourceType = typeof(Labels), Name = "Password")]
        public Password Password { get; set; }

        public Email Email { get; set; }

        public LocalPasswordModel()
        {
            this.Password = new Password();
            this.Email = new Email();
        }
    }

    public class LoginModel
    {
        [Required]
        [Display(ResourceType = typeof(Labels), Name = "UserName")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(ResourceType = typeof(Labels), Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me")]
        public bool RememberMe { get; set; }
    }
}
