//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using PagedList;
using System;
using System.Collections.Generic;
using Wlog.BLL.Entities;

namespace Wlog.Web.Models
{
    /// <summary>
    /// model used to draw log list page. Logs are retrieved by ajax call
    /// </summary>
    public class LogListModel
    {
        public Guid ApplicationId { get; set; }
        public List<ApplicationEntity> Apps { get; set; }
       
    }
}