//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.Collections.Generic;
using Wlog.BLL.Classes;

namespace Wlog.Web.Models
{
    /// <summary>
    /// Model that hold a set of message for a given application
    /// i.e. to show top 10 logs for app
    /// </summary>
    public class MessagesListModel
    {
        public string ApplicationName { get; set; }

        public Guid IdApplication { get; set; }          
              
        public List<LogMessage> Messages {get;set;}
    }
}