//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using Newtonsoft.Json;
using NLog.Config;
using NLog.Targets;
using System;
using Wlog.Clients.Classes;
using Wlog.Clients.Helpers;

namespace NLog.Wlog.Clients
{
    [Target("WebTarget")]
    public class WebTarget : TargetWithLayout
    {
        public WebTarget()
        {

            this.Destination = "localhost";
        }

        public WebTarget(String destination)
        {
            this.Destination = destination;

        }

        [RequiredParameter]
        public string Destination { get; set; }

        [RequiredParameter]
        public string ApplicationKey { get; set; }

        protected override void Write(LogEventInfo logEvent)
        {
            string logMessage = this.Layout.Render(logEvent);

            LogMessage entry = new LogMessage();
            entry.Message = logMessage;
            entry.SourceDate = DateTime.Now;
            entry.ApplicationKey = ApplicationKey;
            entry.Level = logEvent.Level.ToString();

            LogHelper.DoRequest(Destination, JsonConvert.SerializeObject(entry));
        }


       
    }

}
