//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wlog.Library.BLL.Classes
{
    public class AssemblyMetadata
    {
        public string Title { get; set; }
        public string Copyright { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public string FullName { get; set; }
        public string Culture { get; set; }
        public string Architecture { get; set; }
        public string PublicKeyToken { get; set; }

    }
}
