//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wlog.BLL.Classes
{
    public static class Constants
    {
        public static class Roles
        {
            public static String Admin = "ADMIN";
            public static String Read = "READ";
            public static String Write = "WRITE";
}
    }
}