//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wlog.BLL.Classes
{
    public static class Constants
    {
        public static class DictionaryNames
        {
            public const string Main = "MAIN";
        }
            public static class Roles
        {
            public const string Admin = "ADMIN";
            public const string WriteLog = "WRITELOG";
            public const string Login = "LOGIN";
            public const string ReadLog = "READLOG";
            public const string CreateApp = "CREATEAPP";
            public const string AppWriter = "APPWRITER";
        }

        public static class Profiles
        {
            public static String Admin = "ADMIN";
            public static String ApiUser = "APIUSER";
            public static String StandardUser = "STANDARDUSER";
            public static String Reader = "READER";
        }
    }
}