//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;

namespace Wlog.Test.Tests
{
    
    public class MiscTest
    {
        [Fact]
        public void TestMethod()
        {
            Assert.True(1 == 1);
        }



        [Fact, Trait("LoadTest","LoadTest")]
        public void AlwaysFailButSkipped()
        {
            Assert.True(1 != 1);
        }

        [Fact, Trait("ExcludedFromCI", "ExcludedFromCI")]
        public void AlwaysFailButSkipped2()
        {
            Assert.True(1 != 1);
        }
    }
}
