//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Wlog.BLL.Entities;
using Wlog.Library.BLL.Reporitories;

namespace Wlog.Web.Models.User
{
    
    /// <summary>
    /// Class used to edit an existing user
    /// </summary>
    public class EditUser
    {
        public UserEntity DataUser { get; set; }
        public List<UserApps> Apps { get; set; }
        public IEnumerable<RolesEntity> RoleList
        {
            get
            {
                List<RolesEntity> role = RepositoryContext.Current.Roles.GetAllRoles(Library.BLL.Enums.RoleScope.Application);
                role.Add(new RolesEntity { RoleName = "No Role" });
                return role;
            }
        }

        public EditUser()
        {
            this.Apps = new List<UserApps>();
        }
    }
}