//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.ComponentModel.DataAnnotations;
using Wlog.Web.Resources;

namespace Wlog.Web.Models.User
{
    /// <summary>
    /// Model to store user data
    /// </summary>
    public class UserData
    {
        public virtual Guid Id { get; set; }

        [Display(ResourceType = typeof(Labels), Name = "UserName")]
        public virtual string Username { get; set; }

        public virtual string Email { get; set; }

        [Display(Name = "IsAdmin")]
        public virtual bool IsAdmin { get; set; }

        [DataType(DataType.Date)]
        [Display(ResourceType = typeof(Labels), Name = "LastLogin")]
        public virtual DateTime LastLoginDate { get; set; }

        [DataType(DataType.Date)]
        [Display(ResourceType = typeof(Labels), Name = "CreationDate")]
        public virtual DateTime CreationDate { get; set; }

        [Display(ResourceType = typeof(Labels), Name = "IsOnline")]
        public virtual bool IsOnLine { get; set; }
    }
}