//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Wlog.Web.Models.User
{
    /// <summary>
    /// model to store user data
    /// </summary>
    public class UserData
    {
        public virtual Guid Id { get; set; }
        [Display(Name = "User name")]
        public virtual string Username { get; set; }
        public virtual string Email { get; set; }
        [Display(Name = "Is Admin")]
        public virtual bool IsAdmin { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Last Login")]
        public virtual DateTime LastLoginDate { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Creation Date")]
        public virtual DateTime CreationDate { get; set; }
        [Display(Name = "Is Online")]
        public virtual bool IsOnLine { get; set; }

    }
}