//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Wlog.BLL.Entities;
using Wlog.DAL.NHibernate.Helpers;
using Wlog.Library.BLL.DataBase;
using Wlog.Library.BLL.Interfaces;

namespace Wlog.Library.BLL.Reporitories
{
    public class RolesRepository : IRepository
    {

        private static UnitFactory unitFactory;

        public RolesRepository()
        {
            unitFactory = new UnitFactory();
        }

        public List<RolesEntity> GetAllApplicationRoles(ApplicationEntity applicationEntity)
        {
            using (IUnitOfWork uow = unitFactory.GetUnit(this))
            {
                uow.BeginTransaction();
                if (applicationEntity != null)
                {
                    List<Guid> ids = uow.Query<AppUserRoleEntity>()
                        .Where(x => x.ApplicationId.Equals(applicationEntity.IdApplication))
                        .Select(x => x.RoleId).ToList();
                    return uow.Query<RolesEntity>().Where(x => ids.Contains(x.Id)).ToList();
                }
            }
            return null;
        }

        public List<AppUserRoleEntity> GetApplicationRolesForUser(UserEntity userEntity)
        {
            using (IUnitOfWork uow = unitFactory.GetUnit(this))
            {
                uow.BeginTransaction();
                return uow.Query<AppUserRoleEntity>().Where(c => c.UserId.Equals(userEntity.Id)).ToList();
            }
        }

        public RolesEntity GetRoleByName(string rolename)
        {
            using (IUnitOfWork uow = unitFactory.GetUnit(this))
            {
                uow.BeginTransaction();
                return uow.Query<RolesEntity>().FirstOrDefault(x => x.RoleName == rolename);
            }
        }

        public bool Save(RolesEntity rolesEntity)
        {
            try
            {
                using (IUnitOfWork uow = unitFactory.GetUnit(this))
                {
                    uow.BeginTransaction();
                    uow.SaveOrUpdate(rolesEntity);
                    uow.Commit();
                }

                return true;
            }
            catch (Exception err)
            {
                //TODO: log here:

            }

            return false;
        }

        public List<RolesEntity> GetAllRoles()
        {
            List<RolesEntity> result = new List<RolesEntity>();
            try
            {
                using (IUnitOfWork uow = unitFactory.GetUnit(this))
                {
                    result.AddRange(uow.Query<RolesEntity>().ToList());
                }
            }
            catch (Exception err)
            {
                //TODO: log here:

            }

            return result;
        }
    }
}
