//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NLog;
using Wlog.DAL.NHibernate.Helpers;
using Wlog.Library.BLL.Classes;
using Wlog.Library.BLL.DataBase;
using Wlog.Library.BLL.Interfaces;

namespace Wlog.Library.BLL.Reporitories
{
    /// <summary>
    /// Repository used to apply schema changes.
    /// </summary>
    public class SystemRepository : IRepository
    {

        public Type GetEntityType()
        {
            throw new Exception("SystemRepository dont manage entities");
        }

        public static Logger logger { get { return LogManager.GetCurrentClassLogger(); } }
        public SystemRepository()
        {

        }

        public void Dispose()
        {
            
        }


        /// <summary>
        /// Apply schema changes
        /// </summary>
        public void ApplySchemaChanges()
        {
            //TODO: what in case of mongo? in that case we should create collection insthead of tables.
            logger.Debug("[repo] entering ApplySchemaChanges");
            NHibernateContext.ApplySchemaChanges();
        }
    }
}
