//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Wlog.DAL.NHibernate.Helpers;
using Wlog.Library.BLL.Classes;
using Wlog.Library.BLL.DataBase;
using Wlog.Library.BLL.Interfaces;

namespace Wlog.Library.BLL.Reporitories
{
    /// <summary>
    /// Repository used to apply schema changes.
    /// </summary>
    public class SystemRepository : EntityRepository
    {
        public SystemRepository()
        {

        }

        public void Dispose()
        {
            
        }

        public void ApplySchemaChanges()
        {
            logger.Debug("[repo] entering ApplySchemaChanges");
            NHibernateContext.ApplySchemaChanges();
        }
    }
}
