//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wlog.Library.BLL.DataBase
{
    internal class MongoContext
    {
        private MongoClient mongoClient;
        public IMongoDatabase DataBase
        {
            get
            {
                return this.mongoClient.GetDatabase(ConfigurationManager.AppSettings["MongoDbNAme"]);
            }
        }
        //Credenziali
        //http://mongodb.github.io/mongo-csharp-driver/2.0/reference/driver/authentication/
        private static MongoContext CreateNewContext()
        {

            MongoContext ctx = new MongoContext();
            ctx.mongoClient = new MongoClient(ConfigurationManager.ConnectionStrings["Mongodb"].ConnectionString);
            return ctx;
        }

        private static MongoContext current;
        public static MongoContext Current
        {
            get
            {
                return current ?? (current = CreateNewContext());
            }
        }
    }
}
