//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using AutoMapper;
using NLog;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Security;
using Wlog.BLL.Classes;
using Wlog.BLL.Entities;
using Wlog.Library.BLL.Reporitories;
using Wlog.Web.Models;

namespace Wlog.Web.Controllers
{
    /// <summary>
    /// Home page controller
    /// </summary>
    public class HomeController : Controller
    {
        private readonly Logger _logger = LogManager.GetCurrentClassLogger();

        // GET: /Home/
        [Authorize(Roles = Constants.Roles.Admin)]
        public ActionResult Index()
        {
            _logger.Debug("[Home]: Index");
            List<ApplicationModel> result = new List<ApplicationModel>();

            if (UserProfileContext.Current.User != null)
            {
                UserEntity currentUser = RepositoryContext.Current.Users.GetByUsername(Membership.GetUser().UserName);
                List<ApplicationEntity> apps = RepositoryContext.Current.Applications.GetAppplicationForUser(currentUser);
                result.AddRange(Mapper.Map<List<ApplicationModel>>(apps));
            }

            return View(result);
        }
    }
}
