//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wlog.Library.BLL.Configuration
{
    public class RepositoryConfiguration : ConfigurationSection
    {
        internal static RepositoryConfiguration GetConfig()
        {
            return (RepositoryConfiguration)System.Configuration.ConfigurationManager.GetSection("RepositoryConfiguration") ?? new RepositoryConfiguration();
        }


        [System.Configuration.ConfigurationProperty("RepositoryCollection")]
        [ConfigurationCollection(typeof(RepositoryCollection), AddItemName = "Repository")]
        internal RepositoryCollection RepositoryCollection
        {
            get
            {
                object o = this["RepositoryCollection"];
                return o as RepositoryCollection;
            }
        }

    }
}
