//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wlog.Library.BLL.Configuration
{
    public class Repository : ConfigurationElement
    {
        [ConfigurationProperty("RepositoryName", IsRequired = true)]
        public string RepositoryName
        {
            get { return this["RepositoryName"] as string; }
        }

        [ConfigurationProperty("DataBase", IsRequired = true)]
        public string DataBase
        {
            get { return this["DataBase"] as string; }
        }
    }
}
