//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Principal;
using System.Threading;
using System.Web;
using System.Web.Http;
using Wlog.BLL.Classes;

namespace Wlog.Web.Code.API
{
    [AllowAnonymous]
    public class LogController : ApiController
    {
        
        // POST api/<controller>
        public void Post([FromBody]LogMessage value)
        {
            if (LogQueue.Current.MaxQueueSize > LogQueue.Current.Count)
            {
                LogQueue.Current.Enqueue(value);
            }
            else
            {
                LogQueue.Current.PersistLog(value);
            }

        }

    }
}