//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using Hangfire;
using Hangfire.Dashboard;
using Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
//using InfoPage.Configuration;
using Microsoft.Owin;
using NLog;
using System.Configuration;

// Wlog.Library.Scheduler.Startup
namespace Wlog.Library.Scheduler
{
   
    /// <summary>
    /// Hangfire startup configuration
    /// </summary>
    public class Startup
    {

        Logger logger = LogManager.GetCurrentClassLogger();

        public void Configuration(IAppBuilder app)
        {
            bool installed = "True".Equals(ConfigurationManager.AppSettings["WlogInstalled"], StringComparison.InvariantCultureIgnoreCase);
            if (!installed)
            {
                logger.Info("Hangfire not started up. install wlog first.");
                return;
            }
            try
            {
                HangfireBootstrapper.Instance.Start();
                var options = new DashboardOptions
                {
                    //trick to disable "back button" in dashboard (otherwise it will refresh just iframe).
                    AppPath = "javascript:parent.document.location.href='" + VirtualPathUtility.ToAbsolute("~") + "';",
                    AuthorizationFilters = new[]
                    {

                    new HangFireAuthorizationFilter()
                },


                };

                app.UseHangfireDashboard("/private/hangfire", options);
                app.UseHangfireServer();
            }
            catch (Exception err)
            {
                logger.Error(err);
            }
        }
    }
}