//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using Hangfire;
using Hangfire.Dashboard;
using Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
//using InfoPage.Configuration;
using Microsoft.Owin;

//Wlog.Web.Code.Jobs.Startup
namespace Wlog.Web.Code.Jobs
{
   
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            var options = new DashboardOptions
            {
                AppPath = VirtualPathUtility.ToAbsolute("~"),
                AuthorizationFilters = new[]
            {
                
                new HangFireAuthorizationFilter()
            }
            };

            app.UseHangfireDashboard("/private/hangfire", options);
            app.UseHangfireServer();

            //InfoPageConfigurator.Configure(app,
            //        x =>
            //        {
            //            x.BaseUrl = "custom-info";
            //            x.ApplicationName = "WLOG";
            //        });
        }
    }
}