//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using NHibernate.Mapping.ByCode;
using NHibernate.Mapping.ByCode.Conformist;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MongoDB.Bson.Serialization.Attributes;
using Wlog.Library.BLL.Interfaces;

namespace Wlog.BLL.Entities
{
    /// <summary>
    /// Entity used for store application
    /// </summary>
    public class ApplicationEntity : IEntityBase
    {
        public override Guid Id
        {
            get
            {
                return IdApplication;
            }
            set
            {
                Id = value;
            }
        }

        /// <summary>
        /// Id of application
        /// </summary>
        public virtual Guid IdApplication { get; set; }

        /// <summary>
        /// name of application
        /// </summary>
        public virtual string ApplicationName { get; set; }

        /// <summary>
        /// Flag; true if application is active
        /// </summary>
        public virtual bool IsActive { get; set; }

        /// <summary>
        /// Date since application is runnning
        /// </summary>
        public virtual DateTime StartDate { get; set; }

        /// <summary>
        /// Date of application dismission
        /// </summary>
        public virtual System.Nullable<DateTime> EndDate { get; set; }

        /// <summary>
        /// key used to trust client calls
        /// </summary>
        public virtual Guid PublicKey { get; set; }

        public ApplicationEntity()
        {
            this.ApplicationName = "Default";
            this.IsActive = true;
            this.StartDate = DateTime.Now;
        }
    }
}
