//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using NHibernate.Mapping.ByCode;
using NHibernate.Mapping.ByCode.Conformist;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MongoDB.Bson.Serialization.Attributes;
using Wlog.Library.BLL.Interfaces;

namespace Wlog.BLL.Entities
{
    /// <summary>
    /// Entity that represent a log entity
    /// </summary>
    public class LogEntity : IEntityBase
    {     

        /// <summary>
        /// Date when log is stored in system
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
        /// <summary>
        /// Date when log is updated 
        /// </summary>
        public virtual DateTime UpdateDate { get; set; }
        public virtual DateTime SourceDate { get; set; }
        public  virtual string Message { get; set; }
        public virtual string Level { get; set; }
        public virtual string Stacktrace { get; set; }
        //[BsonId]
        public virtual Guid Uid
        {
            get
            {
                return this.Id;
            }
            set
            {
                this.Id = value;
            }
        }
        public virtual Guid ApplictionId { get; set; }

        public virtual string Attributes { get; set; }

    }

   
}
