//******************************************************************************
// <copyright file="license.md" company="Wlog project  (https://github.com/arduosoft/wlog)">
// Copyright (c) 2016 Wlog project  (https://github.com/arduosoft/wlog)
// Wlog project is released under LGPL terms, see license.md file.
// </copyright>
// <author>Daniele Fontani, Emanuele Bucaelli</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using NHibernate.Mapping.ByCode;
using NHibernate.Mapping.ByCode.Conformist;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MongoDB.Bson.Serialization.Attributes;
using Wlog.Library.BLL.Interfaces;

namespace Wlog.BLL.Entities
{
    /// <summary>
    /// A role is realated with feature that user can done
    /// </summary>
    public class RolesEntity : IEntityBase
    {
        public virtual string RoleName { get; set; }
        /// <summary>
        /// If scope is global; this role is valid in all application and in every context
        /// </summary>
        public virtual bool GlobalScope { get; set; }
        /// <summary>
        /// if this flag is on role can be assigned at application level
        /// </summary>
        public virtual bool ApplicationScope { get; set; }

        /*
            In most case flag are alternatives. keeping them as two different flags, allow us to be more flexible.
        */
    }
}